services:
  projeto-farmacia-frontend:
    build:
      context: ./frontend
      network: host
    ports:
      - "5173:5173"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    depends_on:
      - projeto-farmacia-backend

  projeto-farmacia-backend:
    build:
      context: ./backend
      network: host
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
      - PORT=3000
      - DATABASE_URL=postgresql://postgres:${POSTGRES_PASSWORD}@projeto-farmacia-db:5432/${POSTGRES_DB}
    volumes:
      - ./backend:/app
      - /app/node_modules
      - ./backend/logs:/app/logs
    depends_on:
      - projeto-farmacia-db
    env_file:
      - ./backend/.env

  projeto-farmacia-db:
    image: postgres:16-alpine
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./backend/db-init:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
    env_file:
      - ./backend/.env

  projeto-farmacia-backup:
    image: prodrigestivill/postgres-backup-local
    restart: always
    volumes:
      - ./backups:/backups
    depends_on:
      - projeto-farmacia-db
    environment:
      - POSTGRES_HOST=projeto-farmacia-db
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - SCHEDULE=@daily
      - BACKUP_KEEP_DAYS=7
      - BACKUP_KEEP_WEEKS=4
      - BACKUP_KEEP_MONTHS=6
    env_file:
      - ./backend/.env

volumes:
  postgres_data:
